=== AneliaBlagoeva/XML/videoLibrary/videolibrary.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT videolibrary (nameSite,siteLink,videos,studios,actors)>
<!ELEMENT nameSite (#PCDATA)>
<!ELEMENT siteLink (#PCDATA)>
<!ELEMENT videos (video+)>
<!ELEMENT video (filmName,duration,country,year,plot,actorsIN)>
<!ELEMENT filmName (#PCDATA)>
<!ELEMENT duration (#PCDATA) >
<!ELEMENT country (#PCDATA) >
<!ELEMENT year (#PCDATA) >
<!ELEMENT plot (#PCDATA) >
<!ELEMENT actorsIN (actor-ref+)>
<!ELEMENT actor-ref (#PCDATA) >
<!ATTLIST actor-ref
              actorID IDREF #REQUIRED >
<!ATTLIST video 
            gendre (action|adventure|comedy|romantic|drama) #REQUIRED
            produced-by IDREF #REQUIRED
            type (movie|tvShow) #REQUIRED>

<!ELEMENT studios (studio+)>
<!ELEMENT studio (studioName,director,address,phone)>
<!ATTLIST studio
              id ID #REQUIRED >
<!ELEMENT studioName (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA) >
<!ELEMENT actors (actor+)>
<!ELEMENT actor (name,countryActor,email)>
<!ATTLIST actor
              gender (M|F) #REQUIRED
              age NMTOKEN #REQUIRED
              id ID #REQUIRED>
<!ELEMENT name (first,last)>
<!ELEMENT first (#PCDATA) >
<!ELEMENT  last (#PCDATA) >
<!ELEMENT countryActor (#PCDATA) >
<!ELEMENT  email (#PCDATA) >

=== AneliaBlagoeva/XML/videoLibrary/videolibrary1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video gendre='action' produced-by='s2' type='movie'>
            <filmName>Седмият син</filmName>
            <duration>103</duration>
            <country>USA</country>
            <year>2014</year>
            <plot>В ера на вълшебства, когато легенди и магия се сблъскват,
                единственият останал воин от мистичен орден (носителят на „Оскар“ Джеф Бриджис) 
                пътува по цялата земя, за да открие герой, който според предсказанията ще се роди
                с невероятни сили – последният Седми син (Бен Барнс).Изтръгнат от спокойния си
                живот на рибар, неподозираният млад герой се впуска в дръзко приключение заедно със
                своя закоравял в битките ментор, за да срази кралица на мрака (Джулиан Мур) и нейната
                армия от свръхестествени убийци, които тя е пратила срещу кралството им.Режисьор на
                СЕДМИЯТ СИН е Сергей Бодром по сценарий на Чарлс Лийвит и Стив Найт и екранен сюжет на
                Мат Грийнбърг, по поредицата романи „Хрониките Уордстоун“ на Джоузеф Дилейни. 
                Продуценти на филма са Бейзъл Иванюк, Томас Тъл и Лайънъл Уиграм. Изпълнителни продуценти
                са Джон Яшни, Брент О’Конър и Алисия Котър със съпродуценти Джилиан Шеър и Ерика Лий. 
                По поредицата романи „Хрониките Уордстоун“ от Джоузеф Дилейни .
            </plot>
            <actorsIN>
                <actor-ref actorID='a1'/>
                <actor-ref actorID='a3'/>
            </actorsIN>
       </video>
        
        
        <video gendre='adventure' produced-by='s1' type='tvShow'>
            <filmName>Игра на тронове</filmName>
            <duration>45</duration>
            <country>USA</country>
            <year>2011</year>
            <plot>С шеметния си бяг от скована в жесток студ страна към земи на вечно лято и охолно безгрижие,
                ИГРА НА ТРОНОВЕ е сказание за владетели и владетелки, воини и чародеи, наемни убийци и незаконородени
                претенденти за власт, появили се във времена на мрачни поличби. Тук странна войнствена орда се сражава
                с мечове, изковани от невиждан от човека метал, жестоко дивашко племе сее безумие сред хората, свиреп
                млад принц от кръвта на дракона разменя сестра си, за да си върне трона, едно дете се губи в сумрака
                между живота и смъртта и една решена на всичко жена предприема опасно пътуване, за да защити това, което
                й е скъпо. Сред заговори и коварства, трагедии и вероломство, победи и насилия, съюзници и врагове, съдбата
                на Старките виси на косъм и всяка от страните се бори за победа в най-смъртоносния конфликт: Играта на тронове.
            </plot>
            <actorsIN>
                <actor-ref actorID='a2'/>
                <actor-ref actorID='a4'/>
            </actorsIN>
        </video>
       
       
       
        <video gendre='action' produced-by='s3' type='movie'>
            <filmName>Железният човек</filmName>
            <duration>126</duration>
            <country>USA</country>
            <year>2008</year>
            <plot>Номинираният за "Оскар" Робърт Дауни Младши е в ролята на Тони Старк
                (Железният човек) в тази история за индустриалеца милиардер и гениален изобретател, който е отвлечен
                и принуден да създаде разрушително оръжие. Вместо това, използвайки интелигентността и гения си, Тони
                създава хай-тек брониран костюм и бяга от похитителите си. Когато разкрива престъпен заговор с глобални
                последици, той влиза в бронирания си костюм и дава обет да защитава света като "Железният човек". 
            </plot>
            <actorsIN>
                <actor-ref actorID='a1'/>
                <actor-ref actorID='a5'/>
            </actorsIN>
        </video>
        
    </videos>
    
    
    <studios>
        <studio id='s1'>
            <studioName>HBO</studioName>
            <director>Дейвид Бениоф</director>
            <address>Ню Йорк, САЩ</address>
            <phone>654512</phone>
        </studio> 
        
        <studio id='s2'>
            <studioName>Titanic Studios</studioName>
            <director>Сергей Бодров</director>
            <address>Москва,Русия</address>
            <phone>654513</phone>
        </studio>  
        
        <studio id='s3'>
            <studioName>Paramount Pictures</studioName>
            <director>Джон Фавро</director>
            <address>Куинс, САЩ</address>
            <phone>654542</phone>
        </studio> 
    </studios>
    
    <actors>
        <actor gender='M' age='66' id='a1'>
            <name>
                <first>Джеф</first>
                <last>Бриджис</last>
            </name>
            <countryActor>САЩ</countryActor>
            <email>Bridges@gmail.com</email>
        </actor>
        
        
        <actor gender='M' age='45' id='a2'>
            <name>
                <first>Николай </first>
                <last>Костер-Валдау</last>
            </name>
            <countryActor>Дания</countryActor>
            <email>Waldau@gmail.com</email>
        </actor>
        
        
        <actor gender='F' age='55' id='a3'>
            <name>
                <first>Джулиан</first>
                <last>Мур</last>
            </name>
            <countryActor>САЩ</countryActor>
                <email>Moore@gmail.com</email>
        </actor>
        
        <actor gender='F' age='42' id='a4'>
            <name>
                <first>Лина</first>
                <last>Хийди</last>
            </name>
            <countryActor>Бермудски острови</countryActor>
            <email>Headey@gmail.com</email>
        </actor>
        
        <actor gender='M' age='50' id='a5'>
            <name>
                <first>Робърт</first>
                <last>Дауни Джуниър</last>
            </name>
            <countryActor>Ню Йорк, САЩ</countryActor>
            <email>Downy@gmail.com</email>
        </actor>
       
    </actors>
</videolibrary>

=== AneliaBlagoeva/XML/videoLibrary/videolibrary4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video gendre='action' produced-by='s2' type='movie'>
            <filmName>Туристът</filmName>
            <duration>103</duration>
            <country>Франция</country>
            <year>2010</year>
            <plot>Франк (Джони Деп) е американски турист, който посещава Италия, за да забрави жената,
                която го изоставя след една голяма любов. Във влака за Венеция с него се запознава
                красивата Елиз (Анджелина Джоли), която го привлича. Франк се отдава на увлечението,
                но в един момент разбира, че всеки контакт с тайнствената дама е опасен за живота му.
            </plot>
            <actorsIN>
                <actor-ref actorID='a1'/>
            </actorsIN>
        </video>
        
        
        <video gendre='adventure' produced-by='s1' type='movie'>
            <filmName>Лара Крофт.Томб Рейдър</filmName>
            <duration>101</duration>
            <country>САЩ</country>
            <year>2001</year>
            <plot>Във филма „Лара Крофт: Томб Рейдър“ („Lara Croft: Tomb Raider“) член на богато аристократично
                семейство, Лара Крофт е „Томб Рейдър”. Тя колекционира древни артефакти от руините на храмове 
                и градове по целия свят и няма нищо против да се подлага на смъртоносни опасности, за да се сдобие с тях.
                Планетите от слънчевата система се събират в планетарно изравняване, което се случва на всеки 5000 години,
                а тайно общество, наречено илюминати, търси талисман, който дава на притежателя си способността да
                контролира времето. В „Лара Крофт: Томб Рейдър“ („Lara Croft: Tomb Raider“) илюминатите се нуждаят от
                часовник-ключ, който да им помогне в издирването, но се налага да намерят талисмана веднага или да чакат до
                следващото планетарно изравняване.Лара случайно открива този ключ, а те го задигат. Като научава за скритите
                им цели, единственото, което й остава, е да вземе ключа, да открие и унищожи талисмана, преди илюминатите
                да се доберат до него.
            </plot>
            <actorsIN>
                <actor-ref actorID='a1'/>
            </actorsIN>
        </video>
        
        
        
        <video gendre='action' produced-by='s3' type='movie'>
            <filmName>Мистър и мисис Смит</filmName>
            <duration>120</duration>
            <country>САЩ</country>
            <year>2005</year>
            <plot>Екшън, в който Джон и Джейн Смит са обикновена семейна двойка с обикновен, поизносен брак. Но всеки от тях
                крие пикантна тайна - всъщност и двамата са легендарни наемни убийци, работещи за конкурентни компании. Когато
                шокиращата истина излиза наяве, Джон и Джейн се изправят един срещу друг. Двамата най-опитни убийци на света
                осъзнават, че живеят под един покрив.
            </plot>
            <actorsIN>
                <actor-ref actorID='a1'/>
            </actorsIN>
        </video>
        
    </videos>
    
    
    <studios>
        <studio id='s1'>
            <studioName>GK Films</studioName>
            <director>Флориан Хенкел фон Донерсмарк</director>
            <address>Германия</address>
            <phone>684512</phone>
        </studio> 
        
        <studio id='s2'>
            <studioName>Paramount Pictures</studioName>
            <director>Саймън Уест</director>
            <address>Великобритания</address>
            <phone>654544</phone>
        </studio>  
        
        <studio id='s3'>
            <studioName>20th Century Fox</studioName>
            <director>Дъг Лайман</director>
            <address>САЩ</address>
            <phone>153542</phone>
        </studio> 
    </studios>
    
    <actors>
        <actor gender='F' age='40' id='a1'>
            <name>
                <first>Анджелина</first>
                <last>Джоли</last>
            </name>
            <countryActor>САЩ</countryActor>
            <email>Jolie@gmail.com</email>
        </actor>

    </actors>
</videolibrary>

=== AneliaBlagoeva/XML/videoLibrary/videolibrary5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video gendre='adventure' produced-by='s1' type='movie'>
            <filmName>Карибски пирати: Проклятието на Черната перла</filmName>
            <duration>143</duration>
            <country>САЩ</country>
            <year>2003</year>
            <plot>Уил Търнър е млад ковач, влюбен в Елизабет Суон, дъщеря на губернатора. Една нощ градът е 
                нападнат от пиратския кораб „Черната перла“, чийто екипаж, предвождан от капитана Хектор Барбоса,
                е прокълнат заради алчността си да са нито живи, нито мъртви. Наглед те са обикновени хора, но не
                могат да бъдат убити, и не изпитват удоволствията от живота, а лунната светлина разкрива истинската
                им същност – живи скелети. За да развалят проклятието, им е нужна кръв от някогашния член на екипажа
                Бил „Каиша“ Търнър, а тъй като той вече не е жив – от някой, в когото тече кръвта му. Елизабет се
                представя пред тях с името Елизабет Търнър, и те я вземат по погрешка за дъщеря на Бил Търнър, и я отвличат.
                Уил Търнър решава да я спаси, но не получава подкрепа от другите. Единствената му надежда е хвърленият 
                в тъмница Джак Спароу. Уил го измъква срещу обещание да окаже помощ в освобождаването на Елизабет.
                Хитрият и изобретателен Джак обаче има и своя цел – да си върне „Черната перла“, на която е бил капитан,
                преди Барбоса да организира бунт срещу него
            </plot>
            <actorsIN>
                <actor-ref actorID='a1'/>
                <actor-ref actorID='a2'/>
                <actor-ref actorID='a5'/>
            </actorsIN>
        </video>
        
        
        <video gendre='adventure' produced-by='s2' type='movie'>
            <filmName>Властелинът на пръстените: Задругата на пръстена</filmName>
            <duration>178</duration>
            <country>Нова Зеландия</country>
            <year>2001</year>
            <plot>Младият хобит Фродо и смелата задруга от приятели и съюзници се впускат в опасна мисия, за да 
                унищожат легендарния Единствен пръстен. По петите им са слугите на злия Саурон, Господарят на
                мрака и създател на Пръстена. Ако Саурон си върне Пръстена, Средната земя е обречена. Тази епична
                история за доброто, злото, приятелството и саможертвата, носител на четири награди Оскар, ще ви
                пренесе в свят, който надминава и най-смелите ви фантазии.
            </plot>
            <actorsIN>
                <actor-ref actorID='a2'/>
                <actor-ref actorID='a3'/>
                <actor-ref actorID='a4'/>
            </actorsIN>
        </video>
        
        <video gendre='action' produced-by='s3' type='movie'>
            <filmName>Дивергенти</filmName>
            <duration>139</duration>
            <country>САЩ</country>
            <year>2014</year>
            <plot>„Дивергенти“ е вълнуващо екшън приключение в един свят, в който хората са разделени на различни
                фракции въз основа на човешките добродетели. Трис Прайър (Шайлийн Уудли) е предупредена, че е различна
                (дивергентна) и никога няма да може да стане част от някоя от групите. Когато разкрива, че един от
                фракционните лидери (Кейт Уинслет) крои заговор за унищожението на всички дивергенти, Трис е принудена да
                започне да се доверява на тайнствен мъж на име Фор (Тио Джеймс), с когото трябва да стигне до отговора на
                един жизненоважен въпрос, преди да е станало твърде късно: Какво прави дивергентите толкова опасни?
            </plot>
            <actorsIN>
                <actor-ref actorID='a6'/>
                <actor-ref actorID='a7'/>
                <actor-ref actorID='a8'/>
            </actorsIN>
        </video>
        
    </videos>
    
    
    <studios>
        <studio id='s1'>
            <studioName>Disney</studioName>
            <director>Гор Вербински</director>
            <address>САЩ</address>
            <phone>555441</phone>
        </studio> 
        
        <studio id='s2'>
            <studioName>Warner Bros. Pictures </studioName>
            <director>Питър Джаксън</director>
            <address>Уелингтън, Нова Зеландия</address>
            <phone>6544044</phone>
        </studio>  
        
        <studio id='s3'>
            <studioName>Summit Entertainment</studioName>
            <director>Нийл Бъргър</director>
            <address>САЩ</address>
            <phone>953542</phone>
        </studio> 
    </studios>
    
    <actors>
        <actor gender='M' age='52' id='a1'>
            <name>
                <first>Джони</first>
                <last>Деп</last>
            </name>
            <countryActor>Кентъки,САЩ</countryActor>
            <email>Depp@gmail.com</email>
        </actor>
        
        
        <actor gender='M' age='38' id='a2'>
            <name>
                <first>Орландо</first>
                <last>Блум</last>
            </name>
            <countryActor>Кентърбъри, Великобритания</countryActor>
            <email>Bloom@gmail.com</email>
        </actor>
        
        
        <actor gender='M' age='34' id='a3'>
            <name>
                <first>Илайджа</first>
                <last>Ууд</last>
            </name>
            <countryActor>Айова, САЩ</countryActor>
            <email>Wood@gmail.com</email>
        </actor>
        
        <actor gender='F' age='46' id='a4'>
            <name>
                <first>Кейт</first>
                <last>Бланшет</last>
            </name>
            <countryActor>Мелбърн,Австралия</countryActor>
            <email>Blanchett@gmail.com</email>
        </actor>
        
        <actor gender='F' age='30' id='a5'>
            <name>
                <first>Кийра</first>
                <last>Найтли</last>
            </name>
            <countryActor>Мидълсекс,Великобритания</countryActor>
            <email>Knightley@gmail.com</email>
        </actor>
        
        <actor gender='F' age='24' id='a6'>
            <name>
                <first>Шейлийн</first>
                <last> Удли</last>
            </name>
            <countryActor>Калифорния, САЩ</countryActor>
            <email>Woodley@gmail.com</email>
        </actor>
        
        <actor gender='M' age='31' id='a7'>
            <name>
                <first>Тео</first>
                <last>Джеймс</last>
            </name>
            <countryActor>Оксфорд,Великобритания</countryActor>
            <email>James@gmail.com</email>
        </actor>
        
        <actor gender='F' age='40' id='a8'>
            <name>
                <first>Кейт</first>
                <last>Уинслет</last>
            </name>
            <countryActor>Рединг, Великобритания</countryActor>
            <email>Winslett@gmail.com</email>
        </actor>
    </actors>
</videolibrary>

=== AneliaBlagoeva/XML/videoLibrary/videolibrary3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video gendre='comedy' produced-by='s2' type='movie'>
            <filmName>Отмъщение по женски</filmName>
            <duration>109</duration>
            <country>USA</country>
            <year>2014</year>
            <plot>Диас се превъплъщава в образа на красива и уверена в себе си жена, която по случайност открива,
                че на пръв поглед перфектния й приятел (в ролята Николай Костър-Уалдау) е всъщност женен и дори
                се среща тайно с няколко други жени. След като се запознава със съпругата му (Лесли Ман) тя бързо
                спечелва нейното доверие и не след дълго двете жени изготвят план с който се надяват да отмъстят
                на мъжа, който ги лъгал толкова много време.
            </plot>
            <actorsIN>
                <actor-ref actorID='a1'/>
            </actorsIN>
        </video>
        
        
        <video gendre='romantic' produced-by='s2' type='movie'>
            <filmName>Тетрадката</filmName>
            <duration>45</duration>
            <country>USA</country>
            <year>2011</year>
            <plot>Като тийнейджъри, между Али (Рейчъл Макадамс) и Ноа (Райън Гослинг) започва започва вихрено ухажване,
                което скоро преминава в нежна интимност. Младата двойка бързо е раздалена от богатите родитерли на Али,
                които настояват, че Ноа е подходящ за нея. Минават няколко години и когато се срещат пак, страстта им
                отново избухва, като принуждава Али да избира между зова на сърцето повелите на класата си.Тази красива 
                приказка има особено значение за по-стар господин (Джеймс Гарнър), който постоянно чете вечната любовна 
                история на възрастната жена (Джина Роуландс) до него. Базиран на литературния бестселър на Николас Старк, 
                „Тетрадката” едновременно ще стопли и разтърси сърцето ви и ще ви заплени със съкрушителната си емоционална
                сила.
            </plot>
            <actorsIN>
                <actor-ref actorID='a2'/>
            </actorsIN>
        </video>
        
        
        
        <video gendre='comedy' produced-by='s3' type='tvShow'>
            <filmName>Двама мъже и половина</filmName>
            <duration>45</duration>
            <country>USA</country>
            <year>2003</year>
            <plot>„Двама мъже и половина” е базиран върху отношенията между богатия композитор-женкар
                Чарли и брат му Алън, който след развода с жена си заживява при него. Във всеки от
                епизодите задължително присъстват жените на чичо Чарли, с които той не се задържа 
                за повече от вечер, синът на Алън – Джейк, както и ексцентричната майка на двамата
                братя. Всичко това, забъркано на едно място, създава доста комични и абсурдни ситуации. 
                В края на осми сезон обаче, при необичайни обстоятелства героят на Чарли Шийн изненадващо
                се сблъсква със смъртта. 
            </plot>
            <actorsIN>
                <actor-ref actorID='a3'/>
            </actorsIN>
        </video>
        
    </videos>
    
    
    <studios>
        <studio id='s1'>
            <studioName>20 Century Fox</studioName>
            <director>Ник Касаветис</director>
            <address>Ню Йорк, САЩ</address>
            <phone>654511</phone>
        </studio> 
        
        <studio id='s2'>
            <studioName>Warner Bros. Pictures</studioName>
            <director>Ник Касаветис</director>
            <address>Ню Йорк, САЩ</address>
            <phone>654511</phone>
        </studio>  
        
        <studio id='s3'>
            <studioName>Warner Bros. Pictures</studioName>
            <director>Лий Арънсън</director>
            <address>Калифорния</address>
            <phone>654500</phone>
        </studio> 
    </studios>
        
    <actors>
        <actor gender='F' age='43' id='a1'>
            <name>
                <first>Камерън</first>
                <last>Диас</last>
            </name>
            <countryActor>САЩ</countryActor>
            <email>Diaz@gmail.com</email>
        </actor>
        
        
        <actor gender='F' age='37' id='a2'>
            <name>
                <first>Рейчъл</first>
                <last>Макадамс</last>
            </name>
            <countryActor>Канада</countryActor>
            <email>McAdams@gmail.com</email>
        </actor>
        
        <actor gender='M' age='50' id='a3'>
            <name>
                <first>Чарли </first>
                <last>Шийн</last>
            </name>
            <countryActor>Ню Йорк, САЩ</countryActor>
            <email>Sheen@gmail.com</email>
        </actor>
    </actors>
</videolibrary>

=== AneliaBlagoeva/XML/videoLibrary/videolibrary2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
    <nameSite>Арена София</nameSite>
    <siteLink>www.arenaSofia.bg</siteLink>
    <videos>
        <video gendre='comedy' produced-by='s2' type='movie'>
            <filmName>Сам вкъщи 1</filmName>
            <duration>103</duration>
            <country>USA</country>
            <year>1990</year>
            <plot>Кевин Маккалистър (Маколи Кълкин) е забравен сам у дома на Коледа, докато неговите родители
                отиват на ваканция със самолет. Той не се страхува, когато разбира, че е останал сам, но вечерта
                е посетен от двама крадци – Хари и Марв (Джо Пеши и Даниъл Стърн). Кевин им прави различни капани,
                за да им попречи. Родителите му осъзнават едва в самолета, че са оставили Кевин сам и майка му се
                качва на кола, щедро предложена от пътуващи музиканти, за да се върне обратно (тъй като по това време
                няма друг полет обратно). Накрая полицията залавя Хари и Марв. Майка му пристига първа, и само минути
                след това пристигат бащата и другите деца, които са хванали следващия полет.
            </plot>
            <actorsIN>
                <actor-ref actorID='a1'/>
            </actorsIN>
        </video>
        
        
        <video gendre='drama' produced-by='s2' type='tvShow'>
            <filmName>Дневниците на вампира</filmName>
            <duration>45</duration>
            <country>USA</country>
            <year>2009</year>
            <plot>Сериалът се заснема в Мистик Фолс в щата Вирджиния, малък град, преследван и заобиколен от
                свръхестествени същества. Поредицата проследява живота на Елена Гилбърт (Нина Добрев), която се 
                влюбва във вампира Стефан Салваторе (Пол Уесли), а скоро се оказва уловена в любовен триъгълник
                между Стефан и неговия по-голям брат, Деймън (Иън Сомърхолдър), които едновременно са преследвани 
                и от миналото, което са имали с Катрин Пиърс/Катерина Петрова. Сериалът също така се фокусира върху
                живота на приятелите на Елена и другите жители на Мистик Фолс. Появява се и нов главен герой, който 
                е един от "първородните" вампири – Клаус
            </plot>
            <actorsIN>
                <actor-ref actorID='a2'/>
                <actor-ref actorID='a3'/>
                <actor-ref actorID='a4'/>
            </actorsIN>
        </video>
        
        
        
        <video gendre='action' produced-by='s3' type='movie'>
            <filmName>Турнирът</filmName>
            <duration>95</duration>
            <country>Великобритания</country>
            <year>2009</year>
            <plot>На всеки 7 години, в някой произволен град се сформира "Турнирът". Кралска битка между 30 
                от най-смъртоносните бойци в света. Последният оцелял печели 10 милиона и титлата
                "Първи в света". Всички битки се заснемат и се излъчват на кодиран канал, където 
                милиардери залагат богатствата си. Играта започва, но дали фаворитите ще са подготвени за това, което ги очаква...
            </plot>
            <actorsIN>
                <actor-ref actorID='a4'/>
            </actorsIN>
        </video>
        
    </videos>
    
    
    <studios>
        <studio id='s1'>
            <studioName>20th Century Fox</studioName>
            <director>Крис Кълъмбъс</director>
            <address>Пенсилвания,САЩ</address>
            <phone>324512</phone>
        </studio> 
        
        <studio id='s2'>
            <studioName>Bonanza Productionss</studioName>
            <director>Кевин Уилямсън</director>
            <address>САЩ</address>
            <phone>752513</phone>
        </studio>  
        
        <studio id='s3'>
            <studioName>AV Pictures</studioName>
            <director>Скот Ман</director>
            <address>Манчестър, Великобритания</address>
            <phone>654542</phone>
        </studio> 
    </studios>
    
    <actors>
        <actor gender='M' age='35' id='a1'>
            <name>
                <first>Маколи</first>
                <last>Кълкин</last>
            </name>
            <countryActor>САЩ</countryActor>
            <email>Culkin@gmail.com</email>
        </actor>
        
        
        <actor gender='M' age='33' id='a2'>
            <name>
                <first>Пол</first>
                <last>Уесли</last>
            </name>
            <countryActor>САЩ</countryActor>
            <email>Wesley@gmail.com</email>
        </actor>
        
        
        <actor gender='F' age='26' id='a3'>
            <name>
                <first>Нина</first>
                <last>Добрева</last>
            </name>
            <countryActor>България</countryActor>
            <email>Dobrev@gmail.com</email>
        </actor>
        
        <actor gender='M' age='37' id='a4'>
            <name>
                <first>Иън</first>
                <last>Сомърхолдър</last>
            </name>
            <countryActor>САЩ</countryActor>
            <email>Somerholder@gmail.com</email>
        </actor>
        
    </actors>
</videolibrary>
